### PR TITLE
Allow apps to be minified when using content instead of url

### PR DESCRIPTION
**Pull request by halemmerich**

### CODE REVIEW

**Comment by gfwilliams** [comment]
My concern with this is that there is then no way of *stopping* a supplied file from being minified, which seems important given the issues with the minifier we have seen. At least before you could say `min.js` in the URL.

What if (and this might work already) you supply `{name, content, url:"fake.js"}` - and we just ensure that if there is `content` already the `url` never gets loaded?

Or, I guess we could add a new tag, `minify:false` which can stop it

**Comment by halemmerich** [comment]
This should only work unconditionally for files without url. The filter for the source url containing `.min.js` still applies to all files defined with an url. So `{name, content, url:"fake.min.js"}` would probably prevent `content` from being minified.

A new tag seems a cleaner and easier to document way for this, especially if there could be theoretically more ways to reference js files than `content` or `uri`.

**Comment by gfwilliams** [comment]
> So {name, content, url:"fake.min.js"} would probably prevent content from being minified.

My point is really, if this works as-is - there is no need for a change at all because `{name, content, url:"fake.js"}` would allow the file to be minified?

There may also be cases (like module?) where there is no `.js` extension in name.

So maybe as you say it makes more sense to have a tag.

* No `minifiy` tag - same behaviour
* No `minifiy:true` force minification
* No `minifiy:false` force no minification

**Comment by halemmerich** [comment]
The workaround seems to work fine without changes, so currently no need for a new tag.

**Comment by gfwilliams** [comment]
Thanks!

**Pull request closed without merging**
